In [1]:
print('hello world')

hello world


In [7]:
import numpy as np
data = np.random.randn(2,3)
data


array([[-0.62405512,  0.84693219,  0.60165386],
       [-0.31686561,  0.34162612,  0.69824773]])

In [8]:
random.uniform(50,3)

NameError: name 'random' is not defined

In [10]:
import random
random.gauss(50, 10)

57.668147327096804

In [19]:
list = []
while len(list) < 50:
    list.append(int(random.gauss(50, 10)))
list

[45,
 43,
 60,
 23,
 53,
 62,
 43,
 42,
 55,
 40,
 48,
 69,
 52,
 40,
 42,
 45,
 67,
 42,
 42,
 61,
 62,
 58,
 53,
 65,
 63,
 50,
 44,
 46,
 68,
 49,
 53,
 42,
 50,
 45,
 41,
 59,
 51,
 37,
 62,
 52,
 62,
 31,
 50,
 40,
 66,
 66,
 53,
 62,
 56,
 46]

In [17]:
arr1 = np.array([56.72225696255514,51.40148502669424,68.41058823728653],dtype=np.int32)
arr1

array([56, 51, 68])

## 神奇索引

In [21]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [23]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [26]:
arr  = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [29]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

## 排序

In [30]:
arr = np.random.randn(5,3)
arr

array([[-0.10574172, -1.004842  , -0.10047693],
       [-0.13922387,  0.68112915,  0.62883457],
       [-1.42629074,  1.65685118, -0.92483824],
       [ 0.22516129, -1.68264845,  1.21184366],
       [ 0.61897482,  0.91148453, -0.91287482]])

In [33]:
arr.sort(1)
arr

array([[-1.004842  , -0.10574172, -0.10047693],
       [-0.13922387,  0.62883457,  0.68112915],
       [-1.42629074, -0.92483824,  1.65685118],
       [-1.68264845,  0.22516129,  1.21184366],
       [-0.91287482,  0.61897482,  0.91148453]])

In [35]:
arr.sort(0)
arr

array([[-1.68264845, -0.92483824, -0.10047693],
       [-1.42629074, -0.10574172,  0.68112915],
       [-1.004842  ,  0.22516129,  0.91148453],
       [-0.91287482,  0.61897482,  1.21184366],
       [-0.13922387,  0.62883457,  1.65685118]])